// <auto-generated />
using System;
using CloudResourceManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloudResourceManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420030731_InicialDb")]
    partial class InicialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CloudResourceManagementSystem.Models.ManagedDatabase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseHourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabaseEngine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Premium")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StorageCapacityGb")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ManagedDatabases");
                });

            modelBuilder.Entity("CloudResourceManagementSystem.Models.VirtualMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseHourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CpuCores")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Premium")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RamMemoryGb")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VirtualMachines");
                });
#pragma warning restore 612, 618
        }
    }
}
